#!/usr/bin/env python

import sys

from chatbot_gui.gui import ChatbotGUI
from rqt_gui.main import Main

plugin = 'chatbot_gui.gui.ChatbotGUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
